### ISSUE TITLE
[담] 간단 코드 리뷰

### ISSUE THREAD

**Issue by j2h30728** [ruehan/nomad-marvel-character#1]
안녕하세요. 한규님.

리액트2기부터 시작해서 리액트3기까지 함께 하게되어서 영광이에요.
친구관계를 유지하기위해서 코드리뷰로 친구비내러왔어요. 원하시지 않으셨다구요? 
이런, 어쩔수 없군요. 착불입니다.

<p align='center' >
<img src='https://github.com/ruehan/nomad-marvel-character/assets/60846068/86670f34-486d-4363-9779-cc182208263d' width=300 />
</p>

package.json 을 열어보고 한규님이 이 프로젝트에 정성을 다하셨다는 것을 느꼈어요. 
저희가 리액트마스터 챌린지를 하며 배웠던 것들을 적용하셨더라구요. 너무 반가웠어요.

아래는 제가 한규님 졸업작품을 보며 궁금점이 들었던 것들과 알려드리고 싶었던 것, 내지는 그냥 제 취향이 담긴 생각을 공유하고 싶은것들을 작성했습니다.

## framer motion

한규님이 사용하신 framer motion 라이브러리 사용 부분에서 궁금했던 점이 있습니다.

아래의 App 파일에서는 AnimatePresence 이 최상단에 불러서 전체 라우터를 감싸고 있습니다. 

[AnumatePresence](https://www.framer.com/motion/animate-presence/)는 해당 링크에서 확인하실 수 있는 것과 같이 DOM에서 제거되는 애니메이션을 추가할때에 적용하는 컴포넌트입니다. 
즉 언마운트 시키는 컴포넌트가 존재할때 사용하는 것이죠. 

AnumatePresence는 넷플릭스 클론 코딩에서 슬라이더를 만들기위해서 사용했습니다. 
언마운트되는 슬라이드는 중앙에서 왼쪽으로 움직이는 애니메이션을 마운트되는 슬라이드는 오른쪽에서 왼쪽으로 움직이는 애니메이션인 것으로 기억합니다.

그래서 아래의 코드에서는 AnimatePresence이 동작하지 않기때문에 삭제하시는 편이 맞지않을까 싶습니다.

```tsx
// App
function App() {
  const darkmode = useRecoilValue(darkMode);
  return (
    <>
      <ThemeProvider theme={darkmode ? darkTheme : lightTheme}>
        <GlobalStyle />
        <AnimatePresence > // 사용하지 않는 코드로 삭제필요
        <BrowserRouter>
          <Header />
          <Routes>
            <Route path="/" Component={HomePage}/>
            <Route path="/character/:id" Component={CharacterDetailPage}></Route>
            <Route path="/about" Component={About}></Route>
          </Routes>
        </BrowserRouter>
        </AnimatePresence>
      </ThemeProvider>
    </>
  );
}
```

음! 그리고 현재 CharacterDetailPage는 언마운트될때 애니메이션이 동작하지 않습니다. 
즉, exit 코드는 동작하지않기때문에 삭제하셔도 무방합니다.

혹시 한규님은 CharaterDetailPage를 어떤 애니메이션으로 구현하고 싶으셨던 걸까요?
전체 Route를 감싸는 `<AnimatePresence>` 와 DetailPage의 exit를 추가하신 것을 유추하건데 혹시 모달처럼 구현하는 것을 생각하셨을까요? 

```tsx
//pages/CharacterDetailPage.tsx
<Container
        initial={{ opacity: 0, scale: 0.1 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.5 }} // 동작하지 않습니다.
      transition={{ duration: 0.6 }}>
```

### 1. 라우팅 방식

사실 저는 react-router 를 사용해서 라우팅을 할때에는 react-router-dom에서의 `createBrowserRouter`를 사용해서 Object로 router를 주로 구축해 사용합니다. 만약 Object가 아닌 JSX만들고 싶다면 `createRoutesFromElements` 을 쓰는 방법도 있습니다. 

해당 내용은 react-router 공시홈페이지 [feature-overview](https://reactrouter.com/en/main/start/overview#feature-overview)에서 바로 확인 가능합니다. 튜토리얼도 잘되어있습니다.

그래서 저는 한규님 방식이 새로웠고 이런 방식은 처음봤기때문에 궁금증이 들었습니다. 

필수적으로 중첩라우팅이 필요한것은 아니지만, 이런 구조라면 중첩라우팅은 편리하게 할 수 있을까? 라는 의문이들었습니다. 그래서 공식문서를 한 번 확인 해보니, 한규님의 방식으로 작성되는 라우터코드방식을 마이그레이션 하는 방법도 함께 작성되어있더라구요.

[FAQ ) But I’ve got stuff between `<BrwoserRouter>` and `<Routes>`](https://reactrouter.com/en/main/upgrading/v6-data#but-ive-got-stuff-between-browserrouter-and-routes) 

### 2. Route의 Component

react-router 공식문서에 Route에서의 Component 내용을 발췌해 왔습니다.
https://reactrouter.com/en/main/route/route
한 번 확인 부탁드립니다.

> **NOTE**
> 
> 
> When using `RouterProvider`, if you do not wish to specify a React element (i.e., `element={<MyComponent />}`) you may specify a `Component` instead (i.e., `Component={MyComponent}`) and React Router will call `createElement` for you internally. You should only do this for `RouterProvider` applications though since using `Component` inside of `<Routes>` will de-optimize React's ability to reuse the created element across renders.
> 

### 3. 에러페이지

프로젝트 구조상에서는 에러페이지를 처리하지 않는 점이 조금 아쉬웠어요. 사용자는 항상 이상행동을 할 가능성을 가지고있는데 제일 쉽게 이상행동을 할 수 있는 방법이 URL을 달리 입력하는 것이 아닐까 싶어요.

현재 구조를 유지한다면, `<Route path="*" Component={ErrorPage}></Route>` 라는 Route를 추가하는 것이 좋지 않을까 라는 의견입니다.

물론, `createBrowserRouter`를 사용한다면    Route 컴포넌트에 `errorElement={<ErrorBoundary />}` 내지는 `ErrorBoundary={ErrorBoundary}` 를 추가하여 페이지 라우팅시 발생하는 에러를 최상단에서 캐치해주는 에러페이지를 손쉽게 생성할 수 있습니다.

네, 맞아요!! `createBrowserRouter` 한번 잡숴보세요!!!

### 위의 내용을 정리해 담님 입맛대로 App파일을 수정한다면?

`createBrowserRouter`으로는 바꾸지않고 한규님 App 파일을 제 입맛대로 수정한다면, 아래의 코드가 되지않을까 싶습니다.

( `<ThemeProvider/>`와 `<GlobalStyle />` 는 적용되는 계층에 존재한다면 어디있든 상관없을 것같습니다. 그저 현재 적용되는 스타일링을 고려하면서, Route 구조를 깔끔하게 보고싶은, 제 욕심에 구조를 배치한 것이니 크게 신경쓰시지 않으셔도 됩니다.)

에러페이지는 제가 임의로 추가했습니다. 

해당 코드는 한규님의 코드샌드박스에서 전부 문제없이 동작함을 확인했습니다.

```tsx
function App() {
  return (
    <BrowserRouter>
      <Routes >
        <Route  element={<Layout/>}>
            <Route path="/" element={<HomePage/>}/>
            <Route path="/character/:id" element={<CharacterDetailPage/>}></Route>
            <Route path="/about" element={<About/>}></Route>
            <Route path="*" element={<ErrorPage/>}></Route>
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

function Layout () {
  const darkmode = useRecoilValue(darkMode);
	return   <ThemeProvider theme={darkmode ? darkTheme : lightTheme}>
	    <GlobalStyle />
			<Header/>
			<Outlet/>
    </ThemeProvider>

}
const ErrorPage = () =>{
  return <div>에러</div>
}
export default App;
```

예술에는 정답이 없듯 코드에도 정답이 없다고 생각해요.
제가 틀렸을 가능성도 농후합니다. 틀렸으면 TA들이 달려와서 때려주겠죠 푸하항

## api

utils/api 파일내에 api 함수를 만들어 놓으셨는데 page 에서는 다시 fetch로 데이터를 부르고 계시더라구요.
api 파일에 존재하는 코드가 너무 아쉬워서 제가 한 번 Home page에서만 해당 api 함수를 교체해봤습니다.

혹시 잊으셨거나 수정예정이셨으면 죄송해요~! 저도 제가 직접 한 번 해보고 싶더라구요! 
십자말풀이에 마지막 칸에 정답을 채우는 것처럼 느껴져서 허락받지않고 진행 해버렸습니다. 푸헹헹

 axios를 사용할때 제네릭에 타입 넣어주는 방법과 함수 표현식에 타입을 적용하여 api로 반환된 값에 타입추론 하는 방법도 같이 버무려서 적용해봤어요. 
해당코드는 코드샌드박스에서 동작이 잘되는 것을 확인했어요.

```tsx
// utils/api.ts
export const getCharacters:(searchQuery?: string)=>Promise<Character[]> = async (searchQuery?: string) => {
    try{
        const response = await axios.get<CharactersData>(BASE_URL, {
           //.. 아래내용은 한규님 코드와 동일함. 타입부분만 확인 해주세요
}
```

```tsx
// pages/HomePage.tsx
useEffect(() => {
    const fetchCharacters = async () => {
      const data = await getCharacters() 
// getCharacters 의 함수에서 함수표현식으로 타입을 적용해주었기 때문에
// data 이 Character[] 타입으로 타입추론 됩니다.
      setCharacters(data);
    };
    fetchCharacters();
  }, []);
```

추후에 해당 프로젝트를 수정할 계획이 있으시다면, 디테일 페이지도 만들어 놓으신 api 함수를 적용해보시면 어떨까요?!

참고로 저도 타입스크립트를 계속해서 배우는 입장이기때문에 해당코드가 잘못 되어있을 수도 있어요! 참고바래요~

> axios에서 데이터를 가져오는 모든 함수에 대해서 공통의 함수타입을 만드는 것은 어떨까? 라는 생각이 오늘 문득 들었습니다.
> 위의 코드와 같이 하나의 함수에만 해당하는 타입이 아닌 axios로 데이터를 가져오는 함수에서 범용성있게 사용할 수 있는 타입이요!
> 현재 프로젝트는 캐릭터 리스트와 캐릭터 디테일 함수겠네요
> ```js
> type GetDatas<T> =(query?:string)=>Promise<T> 
> export const getCharacters:GetDatas<Character[]> = async (searchQuery) => {
> ```
> 요로코롬 사용해보는 것도 한 번 생각해 보시는건 어떨까요? 참고로 타입의 네이밍은 생각나는 대로 지정했습니다.

## Header 컴포넌트

최상단에서 `<GlobalStyle/>` 을 불러서 사용하시고 계시는데 Header 컴포넌트 내에서도 한 번더 불러 사용하고 계시더라구요. 
혹시 이유가 있을까요?!

Header 컴포넌트에서 body 태그의 스타일링을 적용하는 것도 Header 컴포넌트의 역할보다 과한 역할을 진행하고 있는 것 같아요!

그리고 식별자 네이밍에서 조금 헷갈렸던 부분이 있습니다.

1. darMode의 atom 타입을 boolean을 지정하셨습니다. 
‘너 지금 다크모드냐?! 어? 아니냐?!’ 에서 “응/아니오” 라고  대답할수 있겠끔 `isDarkMode` 로 식별자를 변경하시는건 어떨까요?!
2. `<DarkModeBtn/>` 는 다크모드를 컨트롤하는 버튼으로 이해했지만, `<MdLightMode/>` 와 `<MdModeNight/>` 에서 조금 고비가 왔습니다. 
Md가 어떤 뜻을 담고 있는지 작성하고있는 지금도 사실 잘 모르겠어요.헤헤. 
다크모드라면 MdLightMode 가 렌더되고 MdModeNight가 렌더된다는 것은 유추할 수 있지만 해단 컴포넌트가 어떤 역할을 하는 컴포넌트인지 식별자 네이밍으로 확실하게 의미 전달이 된다면 더 좋지않을까요?
이렇게 줄임표를 쓴다면 한규님만 알아 보실 수 있을 것 같아요! 오! 나만의 코드~

(사실 DarkModeBtn 도 DarkModeButton으로 수정하시길 권유 드리고싶어요. 
저도 자주 줄여쓰다가 호되게 당하고나서는 이름에서 부터 어떤 역할을 하는지 명시하는 연습을 항상 하고있습니다 .푸하항) 

```tsx
 function Header() {

    const [darkmode, setDarkMode] = useRecoilState(darkMode); 
		//isDarkMode가 어떨까~

  return (
    <> // GlobalStyle이 사라지면 HeaderContainer가 존재하기 때문에 이부분도 지워됨!
    <GlobalStyle /> // 최상단에서 부르기 때문에 지워도 되지않을까~
    <HeaderContainer> 
      <Logo>Marvel Characters</Logo>
      <Menu>
        <MenuItem to="/">Home</MenuItem>
        <MenuItem to="/about">About</MenuItem>
        <DarkModeBtn onClick={() => setDarkMode(!darkmode)} > 
            {darkmode ? <MdLightMode /> : <MdModeNight />} 
				// 코드를 보고 유추 가능하지만, 식별자 네이밍으로는 불가능!
        </DarkModeBtn>
      </Menu>
    </HeaderContainer>
    </>
  );
}
```

## 마무리

친구비를 주러 왔다고 하면서 도대체 뭐이렇게 많이 썼나 싶죠?  더 친해지고싶어서 그랬던 것같아요. 푸헹헹

<p align='center'>
<img width=300 src='https://github.com/ruehan/nomad-marvel-character/assets/60846068/a1b0e6ad-b4d6-4fd5-ba5b-8560441b6e91'/>
</p>

아무튼, 스타일드 컴포넌트을 파일의 핵심코드 아래에 둔다던가, 스타일 코드는 컴포넌트.styled.ts 파일로 뺴 둔다던가. 등 다른 여러가지들도 코드리뷰에 기재할까 했지만, 이부분은 영서님이 2조분들의 코드리뷰에 재밌고 알차게 작성해주셔서 그 부분을 참고 하시면 더 좋을 것 같아요.
영서님이 엄청 기깔 나게 잘 써주셧더라구요.

위의 내용은 제가 리액트를 해보면서 좋았던 부분들과 한규님도 아셨으면 하는 부분들을 정리해서 작성한 것과 같아요. 저의 경험과 조막만한 지식이 한규님께 도움 되셨으면 좋겠습니다.

혹시나 잘못된 설명이나 이해되지않는 내용, 한규님의 의도와 벗어난 코드해석이 있을 경우에 꼭 말씀 부탁드려요!
꼭~!!

**Comment by YeongseoYoon** [comment]
LGTM

**Comment by YeongseoYoon** [comment]
아 그리고 추가적으로 담님이 말씀하신 이 부분요
```js
{darkmode ? <MdLightMode /> : <MdModeNight />}
 ```
이 부분 아마 react-icons일 거 같은데 맞을까요? 제가 폰으로 확인하고 있어서 자세히는 보지 않았는데,
그런거라면 임포트시에
```js
import { MdLightMode as LightModeIcon  } from "react-icons/md";
```
이런식으로 가능할거에요!! 참고하세요 ㅎㅎ

**Comment by ruehan** [comment]
@j2h30728 
담님의 소중한 코드 리뷰 감사합니다 ㅎㅎ 친구비는 착불로 결제하겠습니다 ㅋㅋㅋㅋ

2기때 졸작이 너무 마음에 들지 않아서 이번에는 실력은 부족해도 최선을 다해보자라는 마음가짐으로 시작했거든요... package.json에 제 마음이 잘 담겨있어서 다행입니다.

하나씩 답변을 해보자면...

### framer motion
#### AnimatePresence
리액트 마스터에서 배웠던 아주 좋은(?) 애니메이션 라이브러리이죠. 그때 좋은 기억이 많아서 연습할겸 졸작에 미리 적용해보려고 사용했는데요. 
이게 참 여러가지 애니메이션을 시도하기도 하고 CharacterDetailPage에 모달형식으로 적용하려고 했었거든요.
하지만 시간도 부족했고 이런저런 핑계를 대면서 완성을 못해서 결국 폐기(?)했는데요. 그때 ```AnimatePresence```(exit도 마찬가지)를 지우지 않았던거죠...
한마디로 없어도 되었던것이 맞습니다... (즉시 리팩토링 가자~)

### react-router
#### 1. 라우팅 방식
라우팅 방식 관련해서는 최근에 계속 NextJS만 쓰다보니까 어떻게 해야할지 모르겠더라구요 그래서 생각나는 방법으로 했던 건데 지금 생각해보니 중첩라우팅이 필요한 상황에서는 조금 불편할수도 있겠다는 생각이 드네요. ```createBrowserRouter```로 리팩토링 해보겠습니다 ㅎㅎ

#### 2. Route의 Component
해당 부분은 한번 읽어보겠습니다.

#### 3. 에러페이지
개발자라면 당연히 에러페이지를 처리해야하는데 그냥 졸작인데 그런거까지 해야하려나? 라는 생각을 가졌던것 같아요.
그 유명한 ```ErrorBoundary``` 잊지 않고 꼭 추가해보겠습니다 ㅎㅎ

### api
원래 api.ts에 axios로 처리를 해두고 사용중이었는데요. 요구사항에 fetch를 사용하라고 되어있었던거 같은데 (아닐수도 있음..) 그걸 보고 고치다보니 api.ts가 의도치 않게 버려졌네요. 사실 fetch를 사용하더라도 api.ts에 새로 작성하면 되는데 그때의 제가 무슨 생각이었는지 참... 어려운 문제도 아닌데 말이죠 ㅋㅋ 이 부분도 리팩토링 해봐야겠네요.

### Header 컴포넌트
```<GlobalStyle />``` 부분이 Header 컴포넌트에서 한 번더 불러지고 있는지 몰랐습니다... 다음부턴 체크 잘해보겠습니다 (체크의 중요성 확인!) 

1. 그리고 식별자 네이밍은 darkMode의 atom 타입이 boolean으로 되어있으니 isDarkMode가 되는것이 좋아보이는데 (사실 저번에도 들었던 얘기인데) 항상 코딩할때마다 계속 다르게 작성하게 되더라구요... 
2. 이 부분은 React-Icons의 문제이기도 하지만 @YeongseoYoon 영서님이 말해준 것 처럼 alias로 지정해주면 된다는걸 알았으니 앞으로는 신경써서 바꿔보겠습니다 ㅋㅋㅋ

다시보니까 부족한 점이 많이 보이네요... 다음 졸작에서는 보완해서 돌아오겠습니다~
